var Sequelize = require('sequelize');

var objTransformer = {
    id: { type: Sequelize.INTEGER(), primaryKey: true, autoIncrement: true },
    uniqueIdVal: { type: Sequelize.STRING(30), unique: 'uniquetransid', allowNull: false },
    Rev: { type: Sequelize.INTEGER() },
    Count: { type: Sequelize.INTEGER() },
    CountryCode: { type: Sequelize.INTEGER() },
    RegionCode: { type: Sequelize.INTEGER() },
    CellID: { type: Sequelize.INTEGER() },
    MeterID: { type: Sequelize.INTEGER() },
    Type: { type: Sequelize.STRING(100) },
    Action: { type: Sequelize.STRING(100) },
    Attribute: { type: Sequelize.STRING(100) },
    Phase: { type: Sequelize.INTEGER() },
    NoOfMeter: { type: Sequelize.INTEGER() },
    StatusTransformer: { type: Sequelize.STRING(100) },
    Line1Voltage: { type: Sequelize.DECIMAL(20) },
    Line1Current: { type: Sequelize.DECIMAL(20) },
    Line1Period: { type: Sequelize.DECIMAL(20) },
    Line1PhaseAngle: { type: Sequelize.INTEGER() },
    THD: { type: Sequelize.INTEGER() },
    ThirdHarm: { type: Sequelize.INTEGER() },
    FifthHarm: { type: Sequelize.INTEGER() },
    SeventhHarm: { type: Sequelize.INTEGER() },
    NinthHarm: { type: Sequelize.INTEGER() },
    EleventhHarm: { type: Sequelize.INTEGER() },
    ThirteenthHarm: { type: Sequelize.INTEGER() },
    FifteenthHarm: { type: Sequelize.INTEGER() },
    AmbientTemperarture: { type: Sequelize.INTEGER() },
    TopTemperature: { type: Sequelize.INTEGER() },
    BottomTemperature: { type: Sequelize.INTEGER() },
    TransformerOilLevel: { type: Sequelize.INTEGER() },
    BatteryVoltage: { type: Sequelize.INTEGER() },
    BatteryStatus: { type: Sequelize.INTEGER() },
    ActiveReceivedCumulativeRate1: { type: Sequelize.DECIMAL(20, 6) },
    ActiveReceivedCumulativeRate2: { type: Sequelize.DECIMAL(20, 6) },
    ActiveReceivedCumulativeRate3: { type: Sequelize.DECIMAL(20, 6) },
    ActiveReceivedCumulativeRate4: { type: Sequelize.DECIMAL(20, 6) },
    ActiveReceivedCumulativeRate_Total: { type: Sequelize.DECIMAL(20, 6) },
    ActiveDeliveredCumulativeRate1: { type: Sequelize.DECIMAL(20, 6) },
    ActiveDeliveredCumulativeRate2: { type: Sequelize.DECIMAL(20, 6) },
    ActiveDeliveredCumulativeRate3: { type: Sequelize.DECIMAL(20, 6) },
    ActiveDeliveredCumulativeRate4: { type: Sequelize.DECIMAL(20, 6) },
    ActiveDeliveredCumulativeRate_Total: { type: Sequelize.DECIMAL(20, 6) },
    Active_m_Total: { type: Sequelize.DECIMAL(20, 6) },
    ReactiveReceivedCumulativeRate1: { type: Sequelize.DECIMAL(20, 6) },
    ReactiveReceivedCumulativeRate2: { type: Sequelize.DECIMAL(20, 6) },
    ReactiveReceivedCumulativeRate3: { type: Sequelize.DECIMAL(20, 6) },
    ReactiveReceivedCumulativeRate4: { type: Sequelize.DECIMAL(20, 6) },
    ReactiveReceivedCumulativeTotal: { type: Sequelize.DECIMAL(20, 6) },
    ReactiveDeliveredCumulativeRate1: { type: Sequelize.DECIMAL(20, 6) },
    ReactiveDeliveredCumulativeRate2: { type: Sequelize.DECIMAL(20, 6) },
    ReactiveDeliveredCumulativeRate3: { type: Sequelize.DECIMAL(20, 6) },
    ReactiveDeliveredCumulativeRate4: { type: Sequelize.DECIMAL(20, 6) },
    ReactiveDeliveredCumulativeTotal: { type: Sequelize.DECIMAL(20, 6) },
    Reactive_m_Total: { type: Sequelize.DECIMAL(20, 6) },
    ApparentReceivedCumulativeRate_1: { type: Sequelize.DECIMAL(20, 6) },
    ApparentReceivedCumulativeRate_2: { type: Sequelize.DECIMAL(20, 6) },
    ApparentReceivedCumulativeRate_3: { type: Sequelize.DECIMAL(20, 6) },
    ApparentReceivedCumulativeRate_4: { type: Sequelize.DECIMAL(20, 6) },
    ApparentReceivedCumulativeRate_Total: { type: Sequelize.DECIMAL(20, 6) },
    ApparentDeliveredCumulativeRate_1: { type: Sequelize.DECIMAL(20, 6) },
    ApparentDeliveredCumulativeRate_2: { type: Sequelize.DECIMAL(20, 6) },
    ApparentDeliveredCumulativeRate_3: { type: Sequelize.DECIMAL(20, 6) },
    ApparentDeliveredCumulativeRate_4: { type: Sequelize.DECIMAL(20, 6) },
    ApparentDeliveredCumulativeRate_Total: { type: Sequelize.DECIMAL(20, 6) },
    Apparent_m_Total: { type: Sequelize.Sequelize.DECIMAL(20, 6) },
    ActiveMaxdemandMonthlyPeak1: { type: Sequelize.DECIMAL(20, 6) },
    ActiveMaxdemandMonthlyPeak2: { type: Sequelize.DECIMAL(20, 6) },
    ActiveMaxdemandMonthlyPeak3: { type: Sequelize.DECIMAL(20, 6) },
    ActiveMaxdemandMonthlyPeak4: { type: Sequelize.DECIMAL(20, 6) },
    ActiveMaxdemandMonthlyPeak: { type: Sequelize.DECIMAL(20, 6) },
    ActiveMaxdemandMonthlyPeak1Date: { type: Sequelize.INTEGER() },
    ActiveMaxdemandMonthlyPeak1Month: { type: Sequelize.INTEGER() },
    ActiveMaxdemandMonthlyPeak1Year: { type: Sequelize.INTEGER() },
    ActiveMaxdemandMonthlyPeak1Hour: { type: Sequelize.INTEGER() },
    ActiveMaxdemandMonthlyPeak1Min: { type: Sequelize.INTEGER() },
    ActiveMaxdemandMonthlyPeak1Sec: { type: Sequelize.INTEGER() },
    ActiveMaxdemandMonthlyPeak2Date: { type: Sequelize.INTEGER() },
    ActiveMaxdemandMonthlyPeak2Month: { type: Sequelize.INTEGER() },
    ActiveMaxdemandMonthlyPeak2Year: { type: Sequelize.INTEGER() },
    ActiveMaxdemandMonthlyPeak2Hour: { type: Sequelize.INTEGER() },
    ActiveMaxdemandMonthlyPeak2Min: { type: Sequelize.INTEGER() },
    ActiveMaxdemandMonthlyPeak2Sec: { type: Sequelize.INTEGER() },
    ActiveMaxdemandMonthlyPeak3Date: { type: Sequelize.INTEGER() },
    ActiveMaxdemandMonthlyPeak3Month: { type: Sequelize.INTEGER() },
    ActiveMaxdemandMonthlyPeak3Year: { type: Sequelize.INTEGER() },
    ActiveMaxdemandMonthlyPeak3Hour: { type: Sequelize.INTEGER() },
    ActiveMaxdemandMonthlyPeak3Min: { type: Sequelize.INTEGER() },
    ActiveMaxdemandMonthlyPeak3Sec: { type: Sequelize.INTEGER() },
    ActiveMaxdemandMonthlyPeak4Date: { type: Sequelize.INTEGER() },
    ActiveMaxdemandMonthlyPeak4Month: { type: Sequelize.INTEGER() },
    ActiveMaxdemandMonthlyPeak4Year: { type: Sequelize.INTEGER() },
    ActiveMaxdemandMonthlyPeak4Hour: { type: Sequelize.INTEGER() },
    ActiveMaxdemandMonthlyPeak4Min: { type: Sequelize.INTEGER() },
    ActiveMaxdemandMonthlyPeak4Sec: { type: Sequelize.INTEGER() },
    ActiveMaxdemandMonthlyPeakDate: { type: Sequelize.INTEGER() },
    ActiveMaxdemandMonthlyPeakMonth: { type: Sequelize.INTEGER() },
    ActiveMaxdemandMonthlyPeakYear: { type: Sequelize.INTEGER() },
    ActiveMaxdemandMonthlyPeakHour: { type: Sequelize.INTEGER() },
    ActiveMaxdemandMonthlyPeakMin: { type: Sequelize.INTEGER() },
    ActiveMaxdemandMonthlyPeakSec: { type: Sequelize.INTEGER() },
    ReactiveMaxdemandMonthlyPeak1: { type: Sequelize.DECIMAL(20, 6) },
    ReactiveMaxdemandMonthlyPeak2: { type: Sequelize.DECIMAL(20, 6) },
    ReactiveMaxdemandMonthlyPeak3: { type: Sequelize.DECIMAL(20, 6) },
    ReactiveMaxdemandMonthlyPeak4: { type: Sequelize.DECIMAL(20, 6) },
    ReactiveMaxdemandMonthlyPeak: { type: Sequelize.DECIMAL(20, 6) },
    ReactiveMaxdemandMonthlyPeak1Date: { type: Sequelize.INTEGER() },
    ReactiveMaxdemandMonthlyPeak1Month: { type: Sequelize.INTEGER() },
    ReactiveMaxdemandMonthlyPeak1Year: { type: Sequelize.INTEGER() },
    ReactiveMaxdemandMonthlyPeak1Hour: { type: Sequelize.INTEGER() },
    ReactiveMaxdemandMonthlyPeak1Min: { type: Sequelize.INTEGER() },
    ReactiveMaxdemandMonthlyPeak1Sec: { type: Sequelize.INTEGER() },
    ReactiveMaxdemandMonthlyPeak2Date: { type: Sequelize.INTEGER() },
    ReactiveMaxdemandMonthlyPeak2Month: { type: Sequelize.INTEGER() },
    ReactiveMaxdemandMonthlyPeak2Year: { type: Sequelize.INTEGER() },
    ReactiveMaxdemandMonthlyPeak2Hour: { type: Sequelize.INTEGER() },
    ReactiveMaxdemandMonthlyPeak2Min: { type: Sequelize.INTEGER() },
    ReactiveMaxdemandMonthlyPeak2Sec: { type: Sequelize.INTEGER() },
    ReactiveMaxdemandMonthlyPeak3Date: { type: Sequelize.INTEGER() },
    ReactiveMaxdemandMonthlyPeak3Month: { type: Sequelize.INTEGER() },
    ReactiveMaxdemandMonthlyPeak3Year: { type: Sequelize.INTEGER() },
    ReactiveMaxdemandMonthlyPeak3Hour: { type: Sequelize.INTEGER() },
    ReactiveMaxdemandMonthlyPeak3Min: { type: Sequelize.INTEGER() },
    ReactiveMaxdemandMonthlyPeak3Sec: { type: Sequelize.INTEGER() },
    ReactiveMaxdemandMonthlyPeak4Date: { type: Sequelize.INTEGER() },
    ReactiveMaxdemandMonthlyPeak4Month: { type: Sequelize.INTEGER() },
    ReactiveMaxdemandMonthlyPeak4Year: { type: Sequelize.INTEGER() },
    ReactiveMaxdemandMonthlyPeak4Hour: { type: Sequelize.INTEGER() },
    ReactiveMaxdemandMonthlyPeak4Min: { type: Sequelize.INTEGER() },
    ReactiveMaxdemandMonthlyPeak4Sec: { type: Sequelize.INTEGER() },
    ReactiveMaxdemandMonthlyPeakDate: { type: Sequelize.INTEGER() },
    ReactiveMaxdemandMonthlyPeakMonth: { type: Sequelize.INTEGER() },
    ReactiveMaxdemandMonthlyPeakYear: { type: Sequelize.INTEGER() },
    ReactiveMaxdemandMonthlyPeakHour: { type: Sequelize.INTEGER() },
    ReactiveMaxdemandMonthlyPeakMin: { type: Sequelize.INTEGER() },
    ReactiveMaxdemandMonthlyPeakSec: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeak1: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeak2: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeak3: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeak4: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeak: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeak1Date: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeak1Month: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeak1Year: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeak1Hour: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeak1Min: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeak1Sec: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeak2Date: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeak2Month: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeak2Year: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeak2Hour: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeak2Min: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeak2Sec: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeak3Date: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeak3Month: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeak3Year: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeak3Hour: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeak3Min: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeak3Sec: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeak4Date: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeak4Month: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeak4Year: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeak4Hour: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeak4Min: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeak4Sec: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeakDate: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeakMonth: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeakYear: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeakHour: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeakMin: { type: Sequelize.INTEGER() },
    ApparentMaxdemandMonthlyPeakSec: { type: Sequelize.INTEGER() },

    THD_1: { type: Sequelize.INTEGER() },
    ThirdHarm_1: { type: Sequelize.INTEGER() },
    FifthHarm_1: { type: Sequelize.INTEGER() },
    SeventhHarm_1: { type: Sequelize.INTEGER() },
    NinthHarm_1: { type: Sequelize.INTEGER() },
    EleventhHarm_1: { type: Sequelize.INTEGER() },
    ThirteenthHarm_1: { type: Sequelize.INTEGER() },
    FifteenthHarm_1: { type: Sequelize.INTEGER() },

    THD_2: { type: Sequelize.INTEGER() },
    ThirdHarm_2: { type: Sequelize.INTEGER() },
    FifthHarm_2: { type: Sequelize.INTEGER() },
    SeventhHarm_2: { type: Sequelize.INTEGER() },
    NinthHarm_2: { type: Sequelize.INTEGER() },
    EleventhHarm_2: { type: Sequelize.INTEGER() },
    ThirteenthHarm_2: { type: Sequelize.INTEGER() },
    FifteenthHarm_2: { type: Sequelize.INTEGER() },

    THD_3: { type: Sequelize.INTEGER() },
    ThirdHarm_3: { type: Sequelize.INTEGER() },
    FifthHarm_3: { type: Sequelize.INTEGER() },
    SeventhHarm_3: { type: Sequelize.INTEGER() },
    NinthHarm_3: { type: Sequelize.INTEGER() },
    EleventhHarm_3: { type: Sequelize.INTEGER() },
    ThirteenthHarm_3: { type: Sequelize.INTEGER() },
    FifteenthHarm_3: { type: Sequelize.INTEGER() },

    Line2Voltage: { type: Sequelize.DECIMAL(20) },
    Line2Current: { type: Sequelize.DECIMAL(20) },
    Line2Period: { type: Sequelize.DECIMAL(20) },
    Line2PhaseAngle: { type: Sequelize.INTEGER() },

    Line3Voltage: { type: Sequelize.DECIMAL(20) },
    Line3Current: { type: Sequelize.DECIMAL(20) },
    Line3Period: { type: Sequelize.DECIMAL(20) },
    Line3PhaseAngle: { type: Sequelize.INTEGER() },

    ReadTimestamp: { type: Sequelize.DATE },
    DBTimestamp: { type: Sequelize.DATE }

}

var objTableProps = {
    timestamps: true,
    freezeTableName: true,
    tableName: 'transformertransactions'
}

module.exports = {
    objTransformer: objTransformer,
    objTableProps: objTableProps
}