var objData = {
    result : {
        "Rev" : 0,
        "Count" : 31,
        "MessageID" : 1,
        "CountryCode" : 0,
        "RegionCode" : 0,
        "CellID" : 1,
        "MeterID" : 0,
        "Type" : "Response",
        "Action" : "EVENTS_ALARM_DATA",
        "Attribute" : "ALL_ALARMS",

        "Transformer" : {
            "Phase" : 3,
            "NoOfMeter" : 0,
            "StatusTransformer" : "Connected",
            "ReadTimestamp" : new Date(),
            "OverVoltage" : 0,
            "UnderVoltage" : 0,
            "OverLoadLine1(MD Alarm)" : 0,
            "OverLoadLine2(MD Alarm)" : 0,
            "OverLoadLine3(MD Alarm)" : 0,
            "OverFrequency" : 0,
            "UnderFrequency" : 0,
            "PowerFailure" : 0,
            "CTOpen" : 0,
            "PTOpen" : 0,
            "OilLevelSensorFailure" : 0,
            "TamperLid" : 0,
            "TamperBox" : 0,
            "LowOilLevel" : 0,
            "HighOilTemperature" : 0,
            "LowBatteryVoltage" : 0,
            "BatteryFailure" : 0,
            "BatteryRemoved" : 0,
            "PrimaryPowerUp" : 0,
            "PrimaryPowerDown" : 0,
            "Non-TechnicalLoss" : 0,
            "MeterConnected" : 0,
            "MeterDisconnected" : 0,
            "Wi-FiCommunicationLoss" : 0,
            "3G/4G/LTECommunicationLoss" : 0,
            "Communicationattemptsexceeded" : 0,
            "UnAuthenticatedConnectionRequest" : 0
        }
    },
    "DBTimestamp" : new Date()
}

var objMeterAlarmData = {
    "DeviceID" : 19,
    "Phase" : 1,
    "Status" : "Connected",
    "ReadTimestamp" : new Date(),
    "VoltageSagLine1" : 0,
    "VoltageSagLine2" : 0,
    "VoltageSagLine3" : 0,
    "VoltageSwellLine1" : 0,
    "VoltageSwellLine2" : 0,
    "VoltageSwellLine3" : 0,
    "VoltageUnbalance" : 0,
    "VoltageCablelossLine1" : 0,
    "VoltageCablelossLine2" : 0,
    "VoltageCablelossLine3" : 0,
    "VoltageTHDOverLimitLine1" : 0,
    "VoltageTHDOverLimitLine2" : 0,
    "VoltageTHDOverLimitLine3" : 0,
    "CurrentTHDOverLimitLine1" : 0,
    "CurrentTHDOverLimitLine2" : 0,
    "CurrentTHDOverLimitLine3" : 0,
    "PrimaryPowerUp" : 0,
    "PrimaryPowerDown" : 0,
    "LongOutagedetection" : 0,
    "ShortOutagedetection" : 0,
    "NonvolatileMemoryFailed" : 0,
    "Clockerrordetected" : 0,
    "LowBatteryVoltage" : 1,
    "FlashMemoryFailed" : 0,
    "Firmwareupgraded" : 0,
    "Demandreset" : 0,
    "TimeSynchronized" : 0,
    "Historylogcleared" : 0,
    "Coverremoval" : 0,
    "Terminalcoverremoval" : 0,
    "MeterDisconnected" : 0,
    "MeterConnected" : 0,
    "Demandresponseofimportactpwr(kW+)" : 0,
    "Demandresponseofexportactpwr(kW-)" : 0,
    "Demandresponseofimportreactpwr(kVar+)" : 0,
    "Demandresponseofexportreactpwr(kVar-)" : 0
};

module.exports = {
    objData : objData,
    objMeterAlarmData : objMeterAlarmData
};