var arrInput = [
    {
        "MeterID" : 21,
        "MeterSerialNumber" : "00000000000000000BWM 1004",
        "ConfigID" : 2,
        "AppIDs" : [],
        "ConfigStatus" : "M",
        "TransformerID" : 1,
        "Status" : "Registered",
        "ConnDisconnStatus" : "Connected",
        "SealID" : "8738968934698463",
        "BiDirectional" : "TRUE",
        "EVMeter" : "True",
        "Meters_Billing" : {
            "BillingDate" : 2,
            "BillingTime" : "2017-02-05T22:29:00.000Z",
            "MeterConsumerNumber" : "5910964390",
            "MeterConsumerName" : "Municipality",
            "MeterConsumerAddress" : "Bird Street and Voortrekker Street",
            "MeterConsumerContactNumber" : "932682306426300",
            "MeterDemandResetDate" : 2,
            "ImpulseCountperKWh" : "1",
            "ImpulseCountPerKVARh" : "1",
            "MeterConsumerCountry" : "South Africa",
            "MeterConsumerState" : "Western Cape",
            "MeterConsumerCity" : "Beaufort West",
            "MeterConsumerZipCode" : "006970"
        },
        "Meters_Communications" : {
            "MeterMeterAdminPassword" : "00000000000000000000",
            "Latitude" : "-32.353681",
            "Longitude" : "22.584755",
            "IP_address_WiFi" : "192.168.3.7",
            "MAC_ID_WiFi" : "68:9e:19:15:53:76",
            "AccessPointPassword " : "1234567890",
            "AccessPointPassword" : "1234567890"
        },
        "Meters_DeviceDetails" : {
            "MeterApptype" : "Commercial",
            "MeterVersion" : "1.0.0",
            "MeterInstallationLocation" : "Out Door",
            "CT_Ratio" : 1,
            "PT_Ratio" : 1,
            "Phase" : 1,
            "Frequency" : 60,
            "RatedVoltage" : 220,
            "MeterNominalCurrent" : "5",
            "MeterMaximumCurrent" : "100",
            "MeterAccuracy" : 1,
            "MeterCompliantToStandards" : 1,
            "MeterMake" : "Tatung",
            "MeterDisconnector" : "No",
            "Circuit_ID" : 1,
            "CT_CalibrationData" : 1,
            "PT_CalibrationData" : 1,
            "MeterType" : 1,
            "CertificationNumber" : 0,
            "UtilityID" : 0,
            "ApplicableStandard" : 0,
            "MeterClass" : 0,
            "ESN" : "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000",
            "CountryCode" : 0,
            "RegionCode" : 0,
            "SSID_Name" : "CELL2_"
        },
        "Meters_Info" : {
            "Energy1" : 1,
            "Energy2" : 1,
            "Energy3" : 1,
            "Energy4" : 1,
            "Demand" : 3,
            "LoadControlDisconnectThreshold" : 1,
            "ReconnectMethod" : 1,
            "DemandIntervalLength" : 3,
            "NumberofSubIntervals" : 1,
            "ColdLoadPickupTimes" : 1,
            "PowerOutageRecognitionTime" : 1,
            "TestModeDemandIntervalLength " : 1,
            "NumberofTestModeSubintervals " : 1,
            "TimetoremaininTestMode" : 1,
            "DailySelfRead" : 1,
            "DailySelfReadTime" : 1,
            "Quantity1" : 3,
            "Quantity2" : 3,
            "Quantity3" : 3,
            "Quantity4" : 3,
            "LoadProfileIntervalLength" : 2,
            "OutageLength(Sec)" : 2,
            "Pulseweight1" : 1,
            "Pulseweight2" : 2,
            "Pulseweight3" : 3,
            "Pulseweight4" : 4,
            "EnableVoltage Monitor" : 1,
            "PhaseSelection" : 2,
            "VoltageMointorIntervalLength" : 2,
            "RMSVoltLoadThreshold(V)" : 230,
            "RMSVoltHighThreshold(V)" : 230,
            "LowVoltageThreshold" : 230,
            "LowVoltageThresholdDeviation/Interval" : 230,
            "HighVoltageThresholdDeviation/Interval" : 230,
            "AllEvents" : 1,
            "BillingDateCleard" : 1,
            "BillingScheduleExpiration" : 1,
            "DemandRestOccured" : 1,
            "HistoryLogCleared" : 1,
            "ConfigurationErrorDetected" : 1,
            "LoadProfileError" : 1,
            "LowBatteryDetected" : 1,
            "PrimaryPowerDown" : 1,
            "CTMultipliers" : 1,
            "VTMultipliers" : 1,
            "RegisterMultipliers" : 1,
            "Lockout:Loginattempts,optical" : 1,
            "Lockout:Logoutminutes,optical" : 1,
            "Lockout:Loginattempts,lan" : 1,
            "Lockout:Logoutminutes,lan" : 1,
            "ConsecutiveLAN" : 1,
            "LanLinkMetric(quality)periodinseconds" : 1
        },
        "RegisteredTime" : new Date("2017-02-06T13:21:29.888Z"),
        "JobID" : "HygnJLXJgW"
    },
    {
        "MeterID" : 22,
        "MeterSerialNumber" : "00000000000000000BWM 1008",
        "ConfigID" : 2,
        "AppIDs" : [],
        "ConfigStatus" : "M",
        "TransformerID" : 1,
        "Status" : "Registered",
        "ConnDisconnStatus" : "Connected",
        "SealID" : "8738968934698463",
        "BiDirectional" : "TRUE",
        "EVMeter" : "True",
        "Meters_Billing" : {
            "BillingDate" : 2,
            "BillingTime" : "2017-02-05T22:35:00.000Z",
            "MeterConsumerNumber" : "5910964390",
            "MeterConsumerName" : "Municipality",
            "MeterConsumerAddress" : "Bird Street and Voortrekker Street",
            "MeterConsumerContactNumber" : "932682306426300",
            "MeterDemandResetDate" : 2,
            "ImpulseCountperKWh" : "1",
            "ImpulseCountPerKVARh" : "1",
            "MeterConsumerCountry" : "South Africa",
            "MeterConsumerState" : "Western Cape",
            "MeterConsumerCity" : "Beaufort West",
            "MeterConsumerZipCode" : "006970"
        },
        "Meters_Communications" : {
            "MeterMeterAdminPassword" : "00000000000000000000",
            "Latitude" : "-32.354085",
            "Longitude" : "22.583908",
            "IP_address_WiFi" : "192.168.3.6",
            "MAC_ID_WiFi" : "68:9e:19:15:53:6a",
            "AccessPointPassword " : "1234567890",
            "AccessPointPassword" : "1234567890"
        },
        "Meters_DeviceDetails" : {
            "MeterApptype" : "Commercial",
            "MeterVersion" : "1.0.0",
            "MeterInstallationLocation" : "Out Door",
            "CT_Ratio" : 1,
            "PT_Ratio" : 1,
            "Phase" : 1,
            "Frequency" : 60,
            "RatedVoltage" : 220,
            "MeterNominalCurrent" : "5",
            "MeterMaximumCurrent" : "100",
            "MeterAccuracy" : 1,
            "MeterCompliantToStandards" : 1,
            "MeterMake" : "Tatung",
            "MeterDisconnector" : "Yes",
            "Circuit_ID" : 1,
            "CT_CalibrationData" : 1,
            "PT_CalibrationData" : 1,
            "MeterType" : 1,
            "CertificationNumber" : 0,
            "UtilityID" : 0,
            "ApplicableStandard" : 0,
            "MeterClass" : 0,
            "ESN" : "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000",
            "CountryCode" : 0,
            "RegionCode" : 0,
            "SSID_Name" : "CELL2_"
        },
        "Meters_Info" : {
            "Energy1" : 1,
            "Energy2" : 1,
            "Energy3" : 1,
            "Energy4" : 1,
            "Demand" : 3,
            "LoadControlDisconnectThreshold" : 1,
            "ReconnectMethod" : 1,
            "DemandIntervalLength" : 3,
            "NumberofSubIntervals" : 1,
            "ColdLoadPickupTimes" : 1,
            "PowerOutageRecognitionTime" : 1,
            "TestModeDemandIntervalLength " : 1,
            "NumberofTestModeSubintervals " : 1,
            "TimetoremaininTestMode" : 1,
            "DailySelfRead" : 1,
            "DailySelfReadTime" : 1,
            "Quantity1" : 3,
            "Quantity2" : 3,
            "Quantity3" : 3,
            "Quantity4" : 3,
            "LoadProfileIntervalLength" : 2,
            "OutageLength(Sec)" : 2,
            "Pulseweight1" : 1,
            "Pulseweight2" : 2,
            "Pulseweight3" : 3,
            "Pulseweight4" : 4,
            "EnableVoltage Monitor" : 1,
            "PhaseSelection" : 2,
            "VoltageMointorIntervalLength" : 2,
            "RMSVoltLoadThreshold(V)" : 230,
            "RMSVoltHighThreshold(V)" : 230,
            "LowVoltageThreshold" : 230,
            "LowVoltageThresholdDeviation/Interval" : 230,
            "HighVoltageThresholdDeviation/Interval" : 230,
            "AllEvents" : 1,
            "BillingDateCleard" : 1,
            "BillingScheduleExpiration" : 1,
            "DemandRestOccured" : 1,
            "HistoryLogCleared" : 1,
            "ConfigurationErrorDetected" : 1,
            "LoadProfileError" : 1,
            "LowBatteryDetected" : 1,
            "PrimaryPowerDown" : 1,
            "CTMultipliers" : 1,
            "VTMultipliers" : 1,
            "RegisterMultipliers" : 1,
            "Lockout:Loginattempts,optical" : 1,
            "Lockout:Logoutminutes,optical" : 1,
            "Lockout:Loginattempts,lan" : 1,
            "Lockout:Logoutminutes,lan" : 1,
            "ConsecutiveLAN" : 1,
            "LanLinkMetric(quality)periodinseconds" : 1
        },
        "RegisteredTime" : new Date("2017-02-06T12:54:19.904Z"),
        "JobID" : "BygH0UQJgb"
    },
    {
        "MeterID" : 1,
        "MeterSerialNumber" : "00000000000000000BWM 1003",
        "ConfigID" : 2,
        "AppIDs" : [],
        "ConfigStatus" : "M",
        "Status" : "Registered",
        "ConnDisconnStatus" : "Connected",
        "SealID" : "8738968934698463",
        "BiDirectional" : "TRUE",
        "EVMeter" : "False",
        "Meters_Billing" : {
            "BillingDate" : 2,
            "BillingTime" : "2017-01-31T08:36:00.000Z",
            "MeterConsumerNumber" : "5910964390",
            "MeterConsumerName" : "Municipality",
            "MeterConsumerAddress" : "Bird Street and Voortrekker Street",
            "MeterConsumerContactNumber" : "932682306426300",
            "MeterDemandResetDate" : 2,
            "ImpulseCountperKWh" : "1",
            "ImpulseCountPerKVARh" : "1",
            "MeterConsumerCountry" : "South Africa",
            "MeterConsumerState" : "Western Cape",
            "MeterConsumerCity" : "Beaufort West",
            "MeterConsumerZipCode" : "006970"
        },
        "Meters_Communications" : {
            "MeterMeterAdminPassword" : "1234567890",
            "Latitude" : "-32.354039",
            "Longitude" : "22.584559",
            "IP_address_WiFi" : "192.168.3.7",
            "MAC_ID_WiFi" : "68:9e:19:15:53:64",
            "AccessPointPassword " : "datatwine@iot",
            "AccessPointPassword" : "datatwine@iot"
        },
        "Meters_DeviceDetails" : {
            "MeterApptype" : "Street Light Load",
            "MeterVersion" : "1.0.0",
            "MeterInstallationLocation" : "Out Door",
            "CT_Ratio" : 1,
            "PT_Ratio" : 1,
            "Phase" : 1,
            "Frequency" : 60,
            "RatedVoltage" : 220,
            "MeterNominalCurrent" : "5",
            "MeterMaximumCurrent" : "100",
            "MeterAccuracy" : 1,
            "MeterCompliantToStandards" : 1,
            "MeterMake" : "Tatung",
            "MeterDisconnector" : "Yes",
            "Circuit_ID" : 1,
            "CT_CalibrationData" : 1,
            "PT_CalibrationData" : 1,
            "MeterType" : 1,
            "CertificationNumber" : 0,
            "UtilityID" : 0,
            "ApplicableStandard" : 0,
            "MeterClass" : 0,
            "ESN" : "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000",
            "CountryCode" : 0,
            "RegionCode" : 0,
            "SSID_Name" : "CELL3_"
        },
        "TransformerID" : 2,
        "Meters_Info" : {
            "Energy1" : 1,
            "Energy2" : 1,
            "Energy3" : 1,
            "Energy4" : 1,
            "Demand" : 3,
            "LoadControlDisconnectThreshold" : 1,
            "ReconnectMethod" : 1,
            "DemandIntervalLength" : 3,
            "NumberofSubIntervals" : 1,
            "ColdLoadPickupTimes" : 1,
            "PowerOutageRecognitionTime" : 1,
            "TestModeDemandIntervalLength " : 1,
            "NumberofTestModeSubintervals " : 1,
            "TimetoremaininTestMode" : 1,
            "DailySelfRead" : 1,
            "DailySelfReadTime" : 1,
            "Quantity1" : 3,
            "Quantity2" : 3,
            "Quantity3" : 3,
            "Quantity4" : 3,
            "LoadProfileIntervalLength" : 2,
            "OutageLength(Sec)" : 2,
            "Pulseweight1" : 1,
            "Pulseweight2" : 2,
            "Pulseweight3" : 3,
            "Pulseweight4" : 4,
            "EnableVoltage Monitor" : 1,
            "PhaseSelection" : 2,
            "VoltageMointorIntervalLength" : 2,
            "RMSVoltLoadThreshold(V)" : 230,
            "RMSVoltHighThreshold(V)" : 230,
            "LowVoltageThreshold" : 230,
            "LowVoltageThresholdDeviation/Interval" : 230,
            "HighVoltageThresholdDeviation/Interval" : 230,
            "AllEvents" : 1,
            "BillingDateCleard" : 1,
            "BillingScheduleExpiration" : 1,
            "DemandRestOccured" : 1,
            "HistoryLogCleared" : 1,
            "ConfigurationErrorDetected" : 1,
            "LoadProfileError" : 1,
            "LowBatteryDetected" : 1,
            "PrimaryPowerDown" : 1,
            "CTMultipliers" : 1,
            "VTMultipliers" : 1,
            "RegisterMultipliers" : 1,
            "Lockout:Loginattempts,optical" : 1,
            "Lockout:Logoutminutes,optical" : 1,
            "Lockout:Loginattempts,lan" : 1,
            "Lockout:Logoutminutes,lan" : 1,
            "ConsecutiveLAN" : 1,
            "LanLinkMetric(quality)periodinseconds" : 1
        },
        "RegisteredTime" : new Date("2017-02-06T07:21:26.051Z"),
        "JobID" : "HJejKyRYJZ"
    },
    {
        "MeterID" : 3,
        "MeterSerialNumber" : "00000000000000000BWM 1024",
        "ConfigID" : 2,
        "AppIDs" : [],
        "ConfigStatus" : "M",
        "TransformerID" : 2,
        "Status" : "Registered",
        "ConnDisconnStatus" : "Connected",
        "SealID" : "2",
        "BiDirectional" : "TRUE",
        "EVMeter" : "True",
        "Meters_Billing" : {
            "BillingDate" : 1,
            "BillingTime" : "2017-02-02T16:46:22.565Z",
            "MeterConsumerNumber" : "123456789012345",
            "MeterConsumerName" : "BeaufortWEST",
            "MeterConsumerAddress" : "BW_TEST2",
            "MeterConsumerContactNumber" : "123456789012345",
            "MeterDemandResetDate" : 4,
            "ImpulseCountperKWh" : "1",
            "ImpulseCountPerKVARh" : "1",
            "MeterConsumerCountry" : "South Africa",
            "MeterConsumerState" : "BW",
            "MeterConsumerCity" : "Beaufort West",
            "MeterConsumerZipCode" : "400708"
        },
        "Meters_Communications" : {
            "MeterMeterAdminPassword" : "00000000000000000000",
            "Latitude" : "-32.355001",
            "Longitude" : "22.584663",
            "IP_address_WiFi" : "192.168.3.3",
            "MAC_ID_WiFi" : "7c:ec:79:fe:3f:34",
            "AccessPointPassword " : "datatwine@iot",
            "AccessPointPassword" : "datatwine@iot"
        },
        "Meters_DeviceDetails" : {
            "MeterApptype" : "Commercial",
            "MeterVersion" : "1.0.0",
            "MeterInstallationLocation" : "Out Door",
            "CT_Ratio" : 1,
            "PT_Ratio" : 1,
            "Phase" : 3,
            "Frequency" : 50,
            "RatedVoltage" : 220,
            "MeterNominalCurrent" : "5",
            "MeterMaximumCurrent" : "100",
            "MeterAccuracy" : 1,
            "MeterCompliantToStandards" : 1,
            "MeterMake" : "Tatung",
            "MeterDisconnector" : "Yes",
            "Circuit_ID" : 1,
            "CT_CalibrationData" : 1,
            "PT_CalibrationData" : 1,
            "MeterType" : 1,
            "CertificationNumber" : 0,
            "UtilityID" : 0,
            "ApplicableStandard" : 0,
            "MeterClass" : 0,
            "ESN" : "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000",
            "CountryCode" : 0,
            "RegionCode" : 0,
            "SSID_Name" : "CELL3_"
        },
        "Meters_Info" : {
            "Energy1" : 1,
            "Energy2" : 1,
            "Energy3" : 1,
            "Energy4" : 1,
            "Demand" : 3,
            "LoadControlDisconnectThreshold" : 1,
            "ReconnectMethod" : 1,
            "DemandIntervalLength" : 3,
            "NumberofSubIntervals" : 1,
            "ColdLoadPickupTimes" : 1,
            "PowerOutageRecognitionTime" : 1,
            "TestModeDemandIntervalLength " : 1,
            "NumberofTestModeSubintervals " : 1,
            "TimetoremaininTestMode" : 1,
            "DailySelfRead" : 1,
            "DailySelfReadTime" : 1,
            "Quantity1" : 3,
            "Quantity2" : 3,
            "Quantity3" : 3,
            "Quantity4" : 3,
            "LoadProfileIntervalLength" : 2,
            "OutageLength(Sec)" : 2,
            "Pulseweight1" : 1,
            "Pulseweight2" : 2,
            "Pulseweight3" : 3,
            "Pulseweight4" : 4,
            "EnableVoltage Monitor" : 1,
            "PhaseSelection" : 2,
            "VoltageMointorIntervalLength" : 2,
            "RMSVoltLoadThreshold(V)" : 230,
            "RMSVoltHighThreshold(V)" : 230,
            "LowVoltageThreshold" : 230,
            "LowVoltageThresholdDeviation/Interval" : 230,
            "HighVoltageThresholdDeviation/Interval" : 230,
            "AllEvents" : 1,
            "BillingDateCleard" : 1,
            "BillingScheduleExpiration" : 1,
            "DemandRestOccured" : 1,
            "HistoryLogCleared" : 1,
            "ConfigurationErrorDetected" : 1,
            "LoadProfileError" : 1,
            "LowBatteryDetected" : 1,
            "PrimaryPowerDown" : 1,
            "CTMultipliers" : 1,
            "VTMultipliers" : 1,
            "RegisterMultipliers" : 1,
            "Lockout:Loginattempts,optical" : 1,
            "Lockout:Logoutminutes,optical" : 1,
            "Lockout:Loginattempts,lan" : 1,
            "Lockout:Logoutminutes,lan" : 1,
            "ConsecutiveLAN" : 1,
            "LanLinkMetric(quality)periodinseconds" : 1
        },
        "RegisteredTime" : new Date("2017-02-04T06:17:15.932Z"),
        "JobID" : "BJlBYxAKkb"
    }        
];

module.exports = {
    data : arrInput
}